CREATE TABLE tx_interamtconnect_domain_model_authority (
	interamt_uid int(11) NOT NULL DEFAULT '0',
	title varchar(255) NOT NULL DEFAULT '',
	storage_uid int(11) NOT NULL DEFAULT '0',
	description text NOT NULL DEFAULT '',
	website varchar(255) NOT NULL DEFAULT ''
);

CREATE TABLE tx_interamtconnect_domain_model_vacancy (
	interamt_uid int(11) NOT NULL DEFAULT '0',
	authority int(11) NOT NULL DEFAULT '0',
	identifier varchar(255) NOT NULL DEFAULT '',
	title varchar(255) NOT NULL DEFAULT '',
	location_street varchar(255) NOT NULL DEFAULT '',
	location_zip varchar(255) NOT NULL DEFAULT '',
	location_city varchar(255) NOT NULL DEFAULT '',
	description text NOT NULL DEFAULT '',
	latitude varchar(255) NOT NULL DEFAULT '',
	longitude varchar(255) NOT NULL DEFAULT '',
	number_of_vacancies int(11) NOT NULL DEFAULT '0',
	contracts varchar(255) NOT NULL DEFAULT '',
	careers varchar(255) NOT NULL DEFAULT '',
	salary_group_from varchar(255) NOT NULL DEFAULT '',
	salary_group_to varchar(255) NOT NULL DEFAULT '',
	tariff_level_from varchar(255) NOT NULL DEFAULT '',
	tariff_level_to varchar(255) NOT NULL DEFAULT '',
	qualification varchar(255) NOT NULL DEFAULT '',
	training varchar(255) NOT NULL DEFAULT '',
	training_duration decimal(5,2) NOT NULL DEFAULT '0',
	responsibilities varchar(255) NOT NULL DEFAULT '',
	subject_area varchar(255) NOT NULL DEFAULT '',
	work_time varchar(255) NOT NULL DEFAULT '',
	weekly_working_time_civil_servant varchar(255) NOT NULL DEFAULT '',
	weekly_working_time_employee varchar(255) NOT NULL DEFAULT '',
	duration_of_employment varchar(255) NOT NULL DEFAULT '',
	limited_to varchar(255) NOT NULL DEFAULT '',
	application_deadline datetime DEFAULT NULL,
	occupation_to varchar(255) NOT NULL DEFAULT '',
	last_changes datetime DEFAULT NULL,
	tender_date datetime DEFAULT NULL,
	application_process varchar(255) NOT NULL DEFAULT '',
	application_url varchar(255) NOT NULL DEFAULT '',
	required_studies text NOT NULL DEFAULT '',
	attachments text NOT NULL DEFAULT '',
	contact_lastname varchar(255) NOT NULL DEFAULT '',
	contact_firstname varchar(255) NOT NULL DEFAULT '',
	contact_salutaion varchar(255) NOT NULL DEFAULT '',
	contact_street varchar(255) NOT NULL DEFAULT '',
	contact_zip varchar(255) NOT NULL DEFAULT '',
	contact_city varchar(255) NOT NULL DEFAULT '',
	contact_authority varchar(255) NOT NULL DEFAULT '',
	contact_phone varchar(255) NOT NULL DEFAULT '',
	contact_mobile varchar(255) NOT NULL DEFAULT '',
	contact_fax varchar(255) NOT NULL DEFAULT '',
	contact_email varchar(255) NOT NULL DEFAULT ''
);
